# Generated by Django 4.2.16 on 2024-11-19 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.CharField(max_length=200)),
                ('order_num', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order_num'],
            },
        ),
        migrations.AlterModelOptions(
            name='playlistreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='playlist',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='saved_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlistreview',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='playlists.playlist'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistreview',
            unique_together={('user', 'playlist')},
        ),
        migrations.DeleteModel(
            name='PlaylistSong',
        ),
        migrations.AddField(
            model_name='playlistvideo',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist'),
        ),
        migrations.RemoveField(
            model_name='playlistreview',
            name='likes',
        ),
    ]
