# Generated by Django 4.2.16 on 2024-11-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
