# Generated by Django 4.2.16 on 2024-11-20 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlists', '0002_playlistvideo_alter_playlistreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistreview',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_playlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
