# Generated by Django 4.2.16 on 2024-11-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_show_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='show_reviews',
            field=models.BooleanField(default=True),
        ),
    ]
