# Generated by Django 4.2.16 on 2024-11-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='images/default.png', upload_to='profile_images/', verbose_name=' '),
        ),
    ]
