# Generated by Django 5.1.1 on 2024-11-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('audience_acc', models.IntegerField()),
                ('director', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('poster_url', models.URLField(max_length=500)),
                ('plot', models.TextField()),
                ('actors', models.CharField(max_length=500)),
                ('production_year', models.CharField(max_length=4)),
                ('nation', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
