# Generated by Django 4.2.16 on 2024-11-19 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='production_year',
            new_name='open_year',
        ),
    ]
